on:
  push:
    branches: [ main ]

jobs:
  bug:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check Python version
      run: |
        which python
        python --version

    - uses: r-lib/actions/setup-r@master

    - name: Check Python version
      run: |
        which python
        python --version

    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Check Python version
      run: |
        which python
        python --version

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
